import localFont from "next/font/local";
import "./globals.css";
import Usarcontexto from "./context/Usarcontexto";
import ComponenteN from "./components/ComponenteN";
import Formulario from "./components/Formulario";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "LALY MOTORS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased h-screen w-full flex justify-center `}>
        <Usarcontexto>
        <Formulario></Formulario>
        </Usarcontexto>
      </body>
    </html>
  );
}
